      - name: Install Repo Tool
        run: |
          # Создаем директорию для бинарных файлов и добавляем ее в PATH
          mkdir -p ${{ github.workspace }}/bin
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
          
          # Скачиваем и устанавливаем утилиту repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ${{ github.workspace }}/bin/repo
          chmod a+x ${{ github.workspace }}/bin/repo

      - name: Initialize and Sync Kernel Source
        run: |
          # Задаем переменные
          KERNEL_DIR="kernel_source"
          MANIFEST_URL="https://android.googlesource.com/kernel/manifest"
          MANIFEST_BRANCH="android-gs-shusky-6.1-android16"
          
          # Создаем и переходим в директорию для исходников
          mkdir -p "$KERNEL_DIR"
          cd "$KERNEL_DIR"
          
          echo "Initializing repo with branch: $MANIFEST_BRANCH"
          repo init --depth=1 -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH"
          
          # Проверяем, не является ли ветка устаревшей (deprecated)
          REMOTE_BRANCH_STATUS=$(git ls-remote --heads "$MANIFEST_URL" "refs/heads/$MANIFEST_BRANCH")
          DEFAULT_MANIFEST_PATH=".repo/manifests/default.xml"
          
          # Если git ls-remote не находит точную ветку, предполагаем, что она может быть deprecated
          if [ -z "$REMOTE_BRANCH_STATUS" ]; then
            echo "Branch '$MANIFEST_BRANCH' not found. Checking for 'deprecated/$MANIFEST_BRANCH'."
            # Изменяем манифест для использования deprecated пути
            sed -i "s|\"refs/heads/${MANIFEST_BRANCH}\"|\"refs/heads/deprecated/${MANIFEST_BRANCH}\"|g" "$DEFAULT_MANIFEST_PATH"
            
            # Проверяем изменения
            echo "Manifest updated to use deprecated branch path."
            grep "deprecated" "$DEFAULT_MANIFEST_PATH"
          fi
          
          echo "Syncing kernel source..."
          repo sync -c -j$(nproc --all) --no-tags --fail-fast
        
      - name: Verify Source Code Structure
        run: |
          echo "Kernel source synced into 'kernel_source' directory."
          echo "Directory structure:"
          ls -lA kernel_source
          echo "Common kernel directory:"
          ls -lA kernel_source/common
