name: Debug Kernel Source via SSH

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug-session:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Таймаут сессии отладки

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maximize Build Space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-swapfile: 'true'

      - name: Install Repo
        run: |
          mkdir -p .bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > .bin/repo
          chmod a+x .bin/repo
          echo "$GITHUB_WORKSPACE/.bin" >> $GITHUB_PATH

      - name: Initialize and Sync Kernel Source
        run: |
          KERNEL_DIR="kernel_source"
          MANIFEST_URL="https://android.googlesource.com/kernel/manifest"
          MANIFEST_BRANCH="android-gs-shusky-6.1-android16"
          
          mkdir -p "$KERNEL_DIR"
          cd "$KERNEL_DIR"
          
          echo "Initializing repo..."
          repo init --depth=1 -u "$MANIFEST_URL" -b "$MANIFEST_BRANCH"
          
          echo "Syncing kernel source..."
          repo sync -c -j$(nproc --all) --no-tags --fail-fast
          
          echo "Sync complete. Source code is in $GITHUB_WORKSPACE/$KERNEL_DIR"

      - name: Setup SSH session for debugging
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
